# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DroneMcpServer < Formula
  desc "MCP server for read-only Drone CI/CD inspection"
  homepage "https://github.com/sqsp/drone-mcp-server"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sqsp/drone-mcp-server/releases/download/v0.7.1/drone-mcp-server-0.7.1-darwin-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c01ae014c324c47052712d5c4970395a80d07f56fdde10777e9b4a242e410d0e"

      def install
        bin.install "drone-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sqsp/drone-mcp-server/releases/download/v0.7.1/drone-mcp-server-0.7.1-darwin-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1be950cadbfc8a9540ae36130da86671e791da9332873830bb8091c5d09b3cc2"

      def install
        bin.install "drone-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sqsp/drone-mcp-server/releases/download/v0.7.1/drone-mcp-server-0.7.1-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1ba2f95bcce4e8b0c5045f0e659bcae8c976107d6fb2e8d78116b8f9094cdbfb"
      def install
        bin.install "drone-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sqsp/drone-mcp-server/releases/download/v0.7.1/drone-mcp-server-0.7.1-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0f259b23cd839d65d2309a1598d6e045cad2b6d1a727b50d309cdccf517880fd"
      def install
        bin.install "drone-mcp-server"
      end
    end
  end
