# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/private_strategy"
class DroneMcpServer < Formula
  desc ""
  homepage "https://github.com/sqsp/drone-mcp-server"
  version "0.7.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sqsp/drone-mcp-server/releases/download/v0.7.3/drone-mcp-server-0.7.3-darwin-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b2e45c52a3d8223c7e02273e34b92ba53e3cddfd5b7f1969e48b5af89c28e96d"

      def install
        bin.install "drone-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sqsp/drone-mcp-server/releases/download/v0.7.3/drone-mcp-server-0.7.3-darwin-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f94fe64467fd5c273a3339dbb4ae2c10a6188eead6015ca297d1de03a1e3843f"

      def install
        bin.install "drone-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sqsp/drone-mcp-server/releases/download/v0.7.3/drone-mcp-server-0.7.3-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "15fddde7bdd33959f6e030d8fa031c2307d8195332418be5d5f4a5d06b00424a"
      def install
        bin.install "drone-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sqsp/drone-mcp-server/releases/download/v0.7.3/drone-mcp-server-0.7.3-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "53a9dbfbd57f194b3300389dfc0011e1be5984906c0e95ce0a12a63412f91459"
      def install
        bin.install "drone-mcp-server"
      end
    end
  end
end
