# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DroneMcpServer < Formula
  desc "MCP server for read-only Drone CI/CD inspection"
  homepage "https://github.com/sqsp/drone-mcp-server"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sqsp/drone-mcp-server/releases/download/v0.7.0/drone-mcp-server-0.7.0-darwin-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "458cfec694aec95f55bd0e886dae1d37bcb86193f0a76c78c0b9eb4e4a2bceab"

      def install
        bin.install "drone-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sqsp/drone-mcp-server/releases/download/v0.7.0/drone-mcp-server-0.7.0-darwin-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "49cd0120b7ade55f5da620f0ba2de9036a0b93a71fdd776334a768f0e47e9c78"

      def install
        bin.install "drone-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sqsp/drone-mcp-server/releases/download/v0.7.0/drone-mcp-server-0.7.0-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6c3cc0436193b6ad25004dbc11256a4f43e06ff9c72d34618f7ea862063788f5"
      def install
        bin.install "drone-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sqsp/drone-mcp-server/releases/download/v0.7.0/drone-mcp-server-0.7.0-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e0d627b33208bfff8c31beac0fcbb8e35ddfc98e908361b5c73e7a75e9ea29a0"
      def install
        bin.install "drone-mcp-server"
      end
    end
  end

  def caveats
    <<~EOS
      drone-mcp-server requires configuration:

      1. Drone credentials:
         export DRONE_SERVER=https://delivery.squarespace.net
         export DRONE_TOKEN=<your_drone_token>

      2. For IDE integration, see:
         https://github.com/sqsp/drone-mcp-server/blob/master/README.md#ide-integration
    EOS
  end

  test do
    system "#{bin}/drone-mcp-server --version"
  end
end
